apiVersion: v1
kind: ConfigMap

metadata:
  name: backend-config
  namespace: three-tier

data:
  CLOUDINARY_API_KEY: ""
  CLOUDINARY_API_SECRET: ""
  CLOUDINARY_CLOUD_NAME: ""

  JWT_EXPIRE: "15m"
  JWT_SECRET: ""

  MAX_PRODUCTS_PER_SHOP: "20"
  MAX_SHOPS_PER_USER: "3"

  MONGO_URI: ""

  NODE_ENV: "production"

  REFRESH_TOKEN_EXPIRE: "7d"
  REFRESH_TOKEN_SECRET: ""

  SHOP_MIN_MEMBERSHIP_DAYS: "7"

  PORT: "8000"
