pipeline {
    agent any

     parameters {
        choice(
        name: 'ACTION',
        choices: ['plan', 'apply', 'destroy'],
        description: 'Choose Terraform action'
    )
    }


    stages {

        stage('Check Terraform Version') {
            steps {
                sh 'terraform version'
                echo "Selected action: ${params.action}"
            }
        }

        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/abhinand-psq/devopsified-FullStack-applciation.git'
            }
        }

       stage('Terraform Init & Validate') {
    steps {
        dir('Jenkins-Server-TF') {
            withAWS(
                credentials: 'aws-cred',
                region: 'ap-south-1'
            ) {
                sh 'terraform init'
                sh 'terraform validate'
            }
        }
    }
}

        stage('Terraform Plan / Apply') {
            steps {
                dir('Jenkins-Server-TF') {
                    withAWS(
                        credentials: 'aws-cred',
                        region: 'ap-south-1'
                    ) {
                        script {
                            if (params.ACTION == 'plan') {
                                sh 'terraform plan -var-file=variables.tfvars'
                            } else if (params.ACTION == 'apply') {
                                sh 'terraform apply -auto-approve  -var-file=variables.tfvars'
                            }
                            else if (params.ACTION == 'destroy') {
        sh 'terraform destroy -auto-approve -var-file=variables.tfvars'
    }
                        }
                    }
                }
            }
        }
    }
}
